[package]
name = "bapi"
version = "0.1.0"
authors = ["psr31 <harryrigg14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magneto = { path = "../magneto" }
sdl2 = "0.34"
rand = "*"